-- 各種テーブル削除
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS users;

-- カテゴリーテーブル
CREATE TABLE categories
(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name TEXT
);

-- tasks テーブル
CREATE TABLE tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER,
    user_id INTEGER,
    title TEXT NOT NULL,
    closing_date DATE,
    importance INTEGER,
    routine INTEGER,
    memo TEXT,
    is_today BOOLEAN DEFAULT FALSE
);

--usersテーブル
CREATE TABLE users
(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name TEXT,
   email TEXT,
   password TEXT,
   last_login_date DATE
);